export type CreditRole =
  | "admin"
  | "moderator"
  | "developer"
  | "seniorhelper"
  | "helper"
  | "goon";

type CreditSection = "faqContributors" | "currentStaff" | "formerStaff";

export type CreditUser = {
  name: string;
  role: CreditRole;
  title: string;
  tags: string[];
  github: string | null;
  dono: string | null;
  avatar: string;
  sections: CreditSection[];
};

export const sectionOrder: { id: CreditSection; label: string }[] = [
  { id: "faqContributors", label: "FAQ Contributors" },
  { id: "currentStaff", label: "Current Staff" },
  { id: "formerStaff", label: "Former Staff" },
];

export const users: CreditUser[] = [
  {
    name: "Astrea",
    role: "admin",
    title: "Owner",
    tags: ["Lead Artemis Developer"],
    github: "https://github.com/Astrea0014",
    dono: null,
    avatar: "/media/discord-avatars/astrea.webp",
    sections: ["currentStaff"],
  },
  {
    name: "Puppetino",
    role: "admin",
    title: "Administrator",
    tags: ["FAQ Founder", "Legacy FAQ", "Discord Bot"],
    github: "https://github.com/Puppetino",
    dono: "https://www.buymeacoffee.com/Puppetino",
    avatar: "/media/discord-avatars/puppetino.webp",
    sections: ["faqContributors", "formerStaff"],
  },
  {
    name: "Midly",
    role: "admin",
    title: "Administrator",
    tags: [],
    github: "https://github.com/midly202",
    dono: null,
    avatar: "/media/discord-avatars/midly.webp",
    sections: ["currentStaff"],
  },
  {
    name: "Muhnkie",
    role: "moderator",
    title: "Moderator",
    tags: [],
    github: null,
    dono: null,
    avatar: "/media/discord-avatars/muhnkie.webp",
    sections: ["currentStaff"],
  },
  {
    name: "Spit",
    role: "moderator",
    title: "Moderator",
    tags: [],
    github: "https://github.com/OgSpit",
    dono: null,
    avatar: "",
    sections: ["currentStaff"],
  },
  {
    name: "Auralicy",
    role: "moderator",
    title: "Moderator",
    tags: [],
    github: null,
    dono: null,
    avatar: "/media/discord-avatars/auralicy.webp",
    sections: ["currentStaff"],
  },
  {
    name: "Xera",
    role: "developer",
    title: "Developer",
    tags: [
      "Lead FAQ Developer",
      "R6S Downloader",
      "Liberator",
      "ThrowbackLoader",
    ],
    github: "https://github.com/Xeralin",
    dono: null,
    avatar: "/media/discord-avatars/xeralin.webp",
    sections: ["currentStaff", "faqContributors"],
  },
  {
    name: "AKrisz2",
    role: "developer",
    title: "Developer",
    tags: ["R6S Downloader"],
    github: "https://github.com/AKrisz2",
    dono: null,
    avatar: "/media/discord-avatars/akrisz.webp",
    sections: ["currentStaff"],
  },
  {
    name: "Benjaminstrike",
    role: "developer",
    title: "Developer",
    tags: ["Discord AI"],
    github: "https://github.com/benjaminstrike",
    dono: null,
    avatar: "/media/discord-avatars/benjaminstrike.gif",
    sections: ["currentStaff"],
  },
  {
    name: "Lordelias",
    role: "developer",
    title: "Developer",
    tags: [],
    github: "https://github.com/LordEliasTM",
    dono: null,
    avatar: "/media/discord-avatars/lordelias.webp",
    sections: ["currentStaff"],
  },
  {
    name: "0xLusion",
    role: "developer",
    title: "Developer",
    tags: [],
    github: null,
    dono: null,
    avatar: "/media/discord-avatars/0xlusion.webp",
    sections: ["currentStaff"],
  },
  {
    name: "JVAV",
    role: "developer",
    title: "Developer",
    tags: ["Legacy FAQ", "R6S Downloader"],
    github: "https://github.com/JOJOVAV",
    dono: "https://buymeacoffee.com/jvav",
    avatar: "/media/discord-avatars/jvav.webp",
    sections: ["currentStaff"],
  },
  {
    name: "Techtical-",
    role: "seniorhelper",
    title: "Senior Helper",
    tags: [],
    github: null,
    dono: null,
    avatar: "/media/discord-avatars/techtical.webp",
    sections: ["currentStaff"],
  },
  {
    name: "Trom",
    role: "helper",
    title: "Helper",
    tags: [],
    github: null,
    dono: null,
    avatar: "/media/discord-avatars/trom.webp",
    sections: ["currentStaff"],
  },
  {
    name: "ConfusingFool93",
    role: "helper",
    title: "Helper",
    tags: [],
    github: "https://github.com/AvacadoWizard120",
    dono: null,
    avatar: "/media/discord-avatars/confusingfool93.webp",
    sections: ["currentStaff"],
  },
  {
    name: "Cauterite",
    role: "helper",
    title: "Helper",
    tags: [],
    github: "https://github.com/Cauterite",
    dono: null,
    avatar: "/media/discord-avatars/cauterite.webp",
    sections: ["currentStaff"],
  },
  {
    name: "dredis-",
    role: "helper",
    title: "Helper",
    tags: [],
    github: null,
    dono: null,
    avatar: "/media/discord-avatars/dredis-.webp",
    sections: ["currentStaff"],
  },
  {
    name: "Onyx",
    role: "helper",
    title: "Helper",
    tags: [],
    github: null,
    dono: null,
    avatar: "/media/discord-avatars/onyx.webp",
    sections: ["currentStaff"],
  },
  {
    name: "Swerve2k",
    role: "helper",
    title: "Helper",
    tags: [],
    github: null,
    dono: null,
    avatar: "/media/discord-avatars/swerve2k.webp",
    sections: ["currentStaff"],
  },
  {
    name: "xanax",
    role: "helper",
    title: "Helper",
    tags: [],
    github: null,
    dono: null,
    avatar: "/media/discord-avatars/xanax.webp",
    sections: ["currentStaff"],
  },
  {
    name: "Lungu",
    role: "moderator",
    title: "Moderator",
    tags: ["ThrowbackLoader"],
    github: "https://github.com/lungu19",
    dono: null,
    avatar: "https://cdn.discordapp.com/embed/avatars/3.png",
    sections: ["formerStaff"],
  },
  {
    name: "Lonewolf",
    role: "goon",
    title: "Goon",
    tags: [],
    github: "https://github.com/BHLoneWolf0",
    dono: null,
    avatar: "/media/discord-avatars/lonewolf.webp",
    sections: ["formerStaff"],
  },
  {
    name: "SlejmUr",
    role: "goon",
    title: "Goon",
    tags: ["R6S Downloader"],
    github: "https://github.com/SlejmUr",
    dono: null,
    avatar: "/media/discord-avatars/slejmur.webp",
    sections: ["formerStaff"],
  },
  {
    name: "AsianStreetMeat",
    role: "goon",
    title: "Goon",
    tags: [],
    github: null,
    dono: null,
    avatar: "/media/discord-avatars/asianstreetmeat.webp",
    sections: ["formerStaff"],
  },
  {
    name: "Bird",
    role: "goon",
    title: "Goon",
    tags: [],
    github: null,
    dono: null,
    avatar: "/media/discord-avatars/bird.webp",
    sections: ["formerStaff"],
  },
  {
    name: "Chæto",
    role: "goon",
    title: "Goon",
    tags: ["Liberator"],
    github: null,
    dono: null,
    avatar: "/media/discord-avatars/cheato.webp",
    sections: ["formerStaff"],
  },
  {
    name: "Darkxrose",
    role: "goon",
    title: "Goon",
    tags: ["Legacy FAQ"],
    github: "https://github.com/Crxptxc",
    dono: null,
    avatar: "/media/discord-avatars/darkxrose.webp",
    sections: ["formerStaff"],
  },
  {
    name: "Seopung",
    role: "goon",
    title: "Goon",
    tags: [],
    github: null,
    dono: null,
    avatar: "/media/discord-avatars/seopung.webp",
    sections: ["formerStaff"],
  },
  {
    name: "Ernie",
    role: "goon",
    title: "Goon",
    tags: [],
    github: "https://github.com/ErnieDaTryHard",
    dono: null,
    avatar: "/media/discord-avatars/ernie.webp",
    sections: ["formerStaff"],
  },
  {
    name: "Gibbou",
    role: "goon",
    title: "Goon",
    tags: [],
    github: null,
    dono: null,
    avatar: "/media/discord-avatars/gibbou.webp",
    sections: ["formerStaff"],
  },
  {
    name: "killahtree",
    role: "goon",
    title: "Goon",
    tags: [],
    github: null,
    dono: null,
    avatar: "/media/discord-avatars/killahtree.webp",
    sections: ["formerStaff"],
  },
  {
    name: "Wil-",
    role: "goon",
    title: "Goon",
    tags: [],
    github: null,
    dono: null,
    avatar: "/media/discord-avatars/wil-.webp",
    sections: ["formerStaff"],
  },
  {
    name: "Pixie",
    role: "goon",
    title: "Goon",
    tags: [],
    github: null,
    dono: null,
    avatar: "/media/discord-avatars/pixie.webp",
    sections: ["formerStaff"],
  },
];
