from typing import Protocol


class Reporter(Protocol):
    def __enter__(self) -> "Reporter": ...
    def __exit__(self, *exc: object) -> bool | None: ...
    def update(self, text: str) -> None: ...
    def succeed(self, text: str) -> None: ...
    def fail(self, text: str) -> None: ...
    def progress(self, fraction: float) -> None: ...


class NullReporter:
    def __enter__(self) -> "NullReporter":
        return self

    def __exit__(self, *exc: object) -> None: ...

    def update(self, text: str) -> None: ...

    def succeed(self, text: str) -> None: ...

    def fail(self, text: str) -> None: ...

    def progress(self, fraction: float) -> None: ...
